#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npm run format:check || (
    echo '🤔🔍🤔 You have some formatting errors... 🤔🔍🤔
            Next format check failed: View the errors above to see why.'
    false;
)

npm run type-check || (
    echo '🤔🔍🤔 You have some type errors... 🤔🔍🤔
            Next type-check failed: View the errors above to see why.'
    false;
)

npm run lint || (
        echo '😤🏀👋😤 Get that weak s**t out of here! 😤🏀👋😤 
                ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
        false; 
)

# If everything passes... Now we can commit
echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'
